name: code style

on:
  push:
    paths:
      - '**.php'
      - 'testbench.yaml'
      - 'phpunit.xml.dist'
      - 'run-tests.yml'
      - 'php-cs-fixer.yml'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.php --allow-risky=yes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
          commit_user_name: Yunus Emre Deligöz
          commit_user_email: ye@deligoz.me
          commit_author: Yunus Emre Deligöz <ye@deligoz.me>
